<?php

namespace AppBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use AppBundle\Form\ServicioType;
use AppBundle\Entity\Servicio;

/**
     * @Route("/gestionServicios")
     */

class GestionServiciosController extends Controller
{
    /**
     * @Route("/nuevoServicio", name="nuevoServicio")
     */
    public function nuevoServicioAction(Request $request)
    {
        
        $servicio = new Servicio();
        //Construyendo el formulario
        $form = $this->createForm(ServicioType::class, $servicio);

        //Reogemos la informacion
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            //Rellenar el Entity servicio
            $servicio = $form->getData();
            $fotoFile=$servicio->getFoto();
            $fileName = $this->generateUniqueFileName().'.'.$fotoFile->guessExtension();
            // Move the file to the directory where brochures are storeds
                $fotoFile->move(
                    $this->getParameter('servicioImg_directory'),
                    $fileName
                );
            $servicio->setFoto("$fileName");
            $servicio->setfechaCreacion(new \DateTime());

            //Almacenar nuevo servicio
            $em = $this->getDoctrine()->getManager();
            $em->persist($servicio);
            $em->flush();
            return $this->redirectToRoute('servicio',array('id' => $servicio->getId()));
        }

        return $this->render('gestionServicios/nuevoServicio.html.twig',array('form'=>$form->createView()));
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

}
