<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'ivory_ck_editor.config_manager' shared service.

include_once $this->targetDirs[3].'\\vendor\\egeloen\\ckeditor-bundle\\Model\\ConfigManagerInterface.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\ckeditor-bundle\\Model\\ConfigManager.php';

$this->services['ivory_ck_editor.config_manager'] = $instance = new \Ivory\CKEditorBundle\Model\ConfigManager();

$instance->setConfigs(array('my_config' => array('toolbar' => 'basic')));
$instance->setDefaultConfig('my_config');

return $instance;
