<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPex3lvl\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPex3lvl/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPex3lvl.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPex3lvl\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerPex3lvl\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Pex3lvl',
    'container.build_id' => '73d43a3e',
    'container.build_time' => 1538183596,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerPex3lvl');
