<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXukufa6\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXukufa6/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXukufa6.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXukufa6\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXukufa6\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Xukufa6',
    'container.build_id' => '632385f0',
    'container.build_time' => 1538603354,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXukufa6');
