<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAgbyfwz\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAgbyfwz/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerAgbyfwz.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerAgbyfwz\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerAgbyfwz\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Agbyfwz',
    'container.build_id' => '7879a832',
    'container.build_time' => 1538434606,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerAgbyfwz');
